### ISSUE TITLE
Memory Problem with Tensorflow 

### ISSUE THREAD

**Issue by kianfa** [MohammadAsadolahi/Reinforcement-learning-algorithm-Deep-Q-learning-for-cryptocurrency-trading#1]
Would you share an implemented version of this project with pytorch? 
I have problem with memory in tensorflow.

**Comment by MohammadAsadolahi** [comment]
Hi and thank you for asking.

Unfortunately, Tensorflow saves the feedforward graph and causes memory eruption when Model(X) is used (the problem is still the same with Model.predict(X) ) in a loop which is the case for reinforcement learning. So far, I wasn't able to find the solution online. 

However, I will deploy the project in pytorch and provide its link in the Readme file during this week.

Best regards.

**Comment by kianfa** [comment]
Thank you.
